[project]
name = "data-observability-agent"
version = "0.1.0"
description = "AI-powered Data Observability Agent"
requires-python = ">=3.11"
dependencies = [
    "streamlit",
    "pandas",
    "numpy",
    "scipy",
    "scikit-learn",
    "plotly",
    "langgraph",
    "groq",
    "python-dotenv",
    "pydantic"
]

[project.scripts]
data-observability-agent = "data_observability_agent:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
